### ISSUE TITLE
ı need a screenshot

### ISSUE THREAD

**Issue by direkfatih** [muraterdemir/DataStructuresandAlgorithms#1]
![BinaryTree](https://user-images.githubusercontent.com/117915103/209966924-0eab5271-1697-4f23-bc61-e2091c373262.png)

**Comment by muraterdemir** [comment]
Like this ? 
![binary](https://user-images.githubusercontent.com/48916488/210009857-2821d858-cb8a-4ef3-9561-91f7b79ac550.JPG)
